apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5175
      targetPort: 5175
      nodePort: 31000
  selector:
    app: frontend
