apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 5175
      targetPort: 5175
  selector:
    app: frontend
